apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateway
  annotations:
    istio-injection: enabled
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: istio-system
    server: "{{ .Values.spec.destination.server }}"
  source:
    path: ""
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: 1.17.1
    chart: base
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: istio-system
    server: "{{ .Values.spec.destination.server }}"
  source:
    path: ""
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: 1.17.1
    chart: istiod
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - .webhooks[0].failurePolicy
