apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  annotations:
    istio-injection: enabled
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - chart: istio-base
            name: istio-base
            namespace: istio-system
          - chart: istiod
            name: istiod
            namespace: istio-system
          - chart: gateway
            name: istio-ingressgateway
            namespace: istio-ingress
  template:
    metadata:
      name: {{`istio-{{name}}`}}
      namespace: argocd
    spec:
      destination:
        namespace: "{{`{{namespace}}`}}"
        server: {{ .Values.spec.destination.server }}
      project: default
      sources:
        - repoURL: "https://istio-release.storage.googleapis.com/charts"
          targetRevision: 1.17.1
          chart: "{{`{{chart}}`}}"
          helm:
            releaseName: "{{`{{name}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
