apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  source:
    path: ""
    repoURL: "https://charts.bitnami.com/bitnami"
    targetRevision: 17.9.3
    chart: redis
    helm:
      parameters:
        - name: "architecture"
          value: replication
        - name: "replica.replicaCount"
          value: "5"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
