apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: default
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 17.9.3
    chart: redis
    helm:
      parameters:
        - name: "architecture"
          value: standalone
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
